### ISSUE TITLE
2019_09_21_Sat 모임

### ISSUE THREAD

**Issue by ghojeong** [study-records/coding-interview-study#13]
앞으로 한 주의 회의록, 계획 등등은 이슈를 만들어서 남기려고 합니다.
한 주가 끝나면 Close 될 예정입니다.

이 이슈는 이번주 모임에서 다룰 사안 들과 회의록을 적겠습니다.
누구나 자유롭게 적어주시면 됩니다.

**Comment by ghojeong** [comment]
오늘 할 일

1. JUnit 및 문제를 풀기까지의 과정 간단히 시연 by 정배형
    - 다른 사람들은 더 좋은 방법 있으면 제시, 혹은 피드백 주기

2. 문제 풀이에 대한 코드 리뷰
    1. 문제를 풀어온 사람들은 gitHub 에서 리뷰를 올리고, 리뷰 페이지에서 코드를 설명한다.
    1. 다른 사람들은 설명 들으며 github 로 피드백을 준다. (이해가 안가는 코드에 대한 질문도 피드백이 될 수 있다.)
    1. 리뷰된 내용이 모두 반영되거나 협의되면 mater 로 머지한다.
  (연습을 통해 모두가 이 과정에 익숙해지면, 오프라인 미팅이 아니라 온라인에서도 자연스럽게 이뤄질 수 있도록 하는게 목표)

**Comment by ghojeong** [comment]
건의사항

문제풀이외에 진도나간 챕터에 대한 이론 설명에 대한 발표를 준비해보자!
- 한 챕터당 한명
- 매주 2챕터를 나가기로 했으므로, 매주 2명 돌아가며 발표를 해보자

발표를 하기 위해 개념을 정리한 문서는 아래 파일에 적어보자.
Chap9_Interview_Questions/0*/README.md

**Comment by JVHE** [comment]
최범균의 TDD 소개 영상 링크
https://www.youtube.com/watch?v=hFXkjZthuzU
보시면 TDD 개념을 간단하게 잡을 수 있습니다.

**Comment by ghojeong** [comment]
다음주 까지 해올 것

이번주는 새로 진도를 나가지 않고,
본격적으로 코드리뷰를 하는 시간을 가지겠습니다.

각자 풀은 문제를 올리시고, 리뷰를 해달라고 닥달해주세요.
한 PR 당 최소 2사람의 approve 가 필요하도록 하겠습니다.

자신이 괴롭히고 싶은 사람을 닥달하면 됩니다.

**Comment by ghojeong** [comment]
다음주 미팅은 토요일 오후 2시 부터 5시까지 신대방역서 만나도록 하겠습니다.

**Comment by jeon3029** [comment]
문제별 interface issue
1.6 String Solution(String s){ return answer;}
1.7 Integer[][] Solution(Integer[][] matrix){return answer;}
2.6 //논의 필요
2.8 //논의 필요
3.3 //논의 필요
3.5 //Stack Solution(Stack s){return stack;}
4.4 boolean Solution(Tree t){retutn true;}
4.6 Node Solution(Node N){return Node;}

**Comment by ghojeong** [comment]
다음주에 챕터를 발표할 사람은 다음과 같습니다.

01 배열과 문자열 / @ghojeong 
02 연결리스트 /  @jeon3029 
03 스택과 큐 / @JVHE 
04 트리와 그래프 / @lqqojin

**Comment by JVHE** [comment]
> 문제별 interface issue
> 1.6 String Solution(String s){ return answer;}
> 1.7 Integer[][] Solution(Integer[][] matrix){return answer;}
> 2.6 //논의 필요
> 2.8 //논의 필요
> 3.3 //논의 필요
> 3.5 //Stack Solution(Stack s){return stack;}
> 4.4 boolean Solution(Tree t){retutn true;}
> 4.6 Node Solution(Node N){return Node;}

좋은 방법 같아요. 저는 찬성

**Comment by ghojeong** [comment]
그리고 @JVHE 는 오늘 JUnit 관련해서 설명한 내용을 정리해서
Chap9_Interview_Questions/README.md 
문서로 만들어주세요.
추후에 합류할지도 모르는 팀원들과 지은씨를 위한 문서화입니다.

**Comment by JVHE** [comment]
> 그리고 @JVHE 는 오늘 JUnit 관련해서 설명한 내용을 정리해서
> Chap9_Interview_Questions/README.md
> 문서로 만들어주세요.
> 추후에 합류할지도 모르는 팀원들과 지은씨를 위한 문서화입니다.

작성 완료했습니다.

**Comment by jeon3029** [comment]
issue close 하겠습니다.
