### ISSUE TITLE
연락처

### ISSUE THREAD

**Issue by ghojeong** [study-records/coding-interview-study#15]
원활한 코드리뷰를 위해 서로 닥달할 수 있도록, 각자의 핸드폰 번호를 포함한 연락처를 적도록 하겠습니다.

**Comment by ghojeong** [comment]
고정완

핸드폰: 010-3878-1459
이메일: ghojeong@gmail.com

**Comment by lqqokim** [comment]
김인수

핸드폰: 010-5098-7618
이메일: kis420404@gmail.com

**Comment by lqqojin** [comment]
윤재진

핸드폰: 010-3803-2633
이메일: lqqojin@gmail.com

**Comment by ghojeong** [comment]
생각해보니 Slack 프로필에 전화번호 넣는게 있었네요 깜빡했습니다.

**Comment by jeon3029** [comment]
저도 Slack에 반영해두었습니다~

**Comment by jeon3029** [comment]
Close 하겠습니다. Slack에 연락처 올려주세요.
