### ISSUE TITLE
폴더 구조 네이밍

### ISSUE THREAD

**Issue by JVHE** [study-records/coding-interview-study#2]
폴더 이름 규칙 수정을 제안합니다.
제가 고려한 사항은 다음과 같습니다.
1. 띄어쓰기나 한글, 특수문자가 없어야 한다.
2. 되도록 책의 목차와 맞아야 한다.
3. 알아보기 쉬워야 한다.

생각한 제안은 다음과 같습니다.

제안 1. 목차의 띄어쓰기를 '_'로 대체. 기술면접의 Chapter N의 경우 ChapterN으로 넣기
I_The_Interview_Process
II_Behind_The_Scenes
VII_Technical_Questions
└ Chapter1_Arrays_and_Strings
   Chapter4_Stacks_and_Queues
제안 2. 대단원 목차는 로마자 표기, 이후 upper camel case
I_TheInterviewProcess
II_BehindTheScenes
VII_TechnicalQuestions
└ Chapter1_ArraysAndStrings
   Chapter4_StacksAndQueues
제안 3. 대단원 목차는 로마자 표기, 이후 lower camel case
I_theInterviewProcess
II_behindTheScenes
VII_technicalQuestions
└ Chapter1_arraysAndStrings
   Chapter4_stacksAndQueues

저는 개인적으로 제안 1을 제안하고 싶습니다. 폴더 구조랑 파일이랑 다른 네이밍이라 구분이 쉬울 것 같아요.

참고: https://stackoverflow.com/questions/6707025/net-naming-standard-for-class-names-with-roman-numerals

의견 부탁드려요.

**Comment by ghojeong** [comment]
만약 실행시에 문제가 생기지 않는다면, 제안 1 이 제일 가독성이 좋기는 하네요.
제안 1로 했을때 문제가 생기지 않는지 (가령 윈도우라던가) 확인해보고,
괜찮으면 제안 1이 제일 마음에 듭니다.

**Comment by lqqojin** [comment]
제안 1의 가독성이 높은 것 같습니다.
그리고 Snake 방식은 윈도우에서 폴더, 파일명 생성하는데 오류가 나지 않습니다.
제안 1의 방식에 동의합니다~

**Comment by lqqojin** [comment]
제안 1의 가독성이 높은 것 같습니다.
그리고 Snake 방식은 윈도우에서 폴더, 파일명 생성하는데 오류가 나지 않습니다.
제안 1의 방식에 동의합니다~
